Repository OFFTORIVER/BJGG, pull requests merged in 2023-03, with the labels that each got.

#172 [2023/03/08] refactor/bbajiConstraints >> BbajiConstraint에 private init 설정
  BJGG/BJGG/Utilities/Constraints.swift
Labels: 🔨 Refactor

#173 [2022/03/09] refactor/weatherManagerErrorCase >> WeatherManagerError의 case명 수정
  BJGG/BJGG/BbajiHome/BbajiHomeViewController.swift
  BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
  BJGG/BJGG/Network/WeatherManager.swift
Labels: 🔨 Refactor

#178 [2023/03/14] refactor/dateVariables >> Weather, WeatherManager 내부 날짜/시간 변수로직 리팩토링
  BJGG/BJGG.xcodeproj/project.pbxproj
  BJGG/BJGG/Extension/Date+Weather.swift
  BJGG/BJGG/Model/Weather.swift
  BJGG/BJGG/Model/WeatherTime.swift
  BJGG/BJGG/Network/WeatherManager.swift
Labels: 🔨 Refactor

#181 [2023/03/16] refactor/BbajiSpotViewControllerComponentsRefactor -> 코드 리팩토링
  BJGG/BJGG.xcodeproj/project.pbxproj
  BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
  BJGG/BJGG/BbajiSpot/UI Component/IconAndLabelView.swift
  BJGG/BJGG/BbajiSpot/UI Component/InfoDescriptionView.swift
  BJGG/BJGG/BbajiSpot/UI Component/LiveMarkView.swift
  BJGG/BJGG/BbajiSpot/UI Component/ScreenSizeControlButton.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraControlView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraGradientView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraStanbyView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotTodayWeatherCollectionView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotTodayWeatherCollectionViewCell.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotWeatherAPIInfoView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotWeatherInfoView.swift
  BJGG/BJGG/Extension/UILabel+CopyLabelText.swift
Labels: 🔨 Refactor

#186 [2023/03/16] feat/liveStreamingVideoTextAnimation > 영상 로딩 페이지 애니메이션 부여
  BJGG/BJGG.xcodeproj/project.pbxproj
  BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraStandbyView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotTodayWeatherCollectionViewCell.swift
Labels: ✨ Feat, :art: Design

#187 [2023/03/17] refactor/bbajiHomeViewControllerMVC >> BbajiHomeViewController, 내부 View UI의 MVC 패턴 리팩토링
  BJGG/BJGG.xcodeproj/project.pbxproj
  BJGG/BJGG/BbajiHome/BbajiHomeViewController.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiHomeBackgroundImageView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListCollectionView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListView/BbajiListCell.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListView/BbajiListCellPreviewView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListView/BbajiListCellShadowView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiListView/BbajiListView.swift
  BJGG/BJGG/BbajiHome/UI Component/BbajiTitleView.swift
  BJGG/BJGG/SceneDelegate.swift
Labels: 🔨 Refactor

#189 [2023/03/23] refactor/BbajiSpotViewController >> Discuss 결정 사항 기반으로 코드 리팩토링
  BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
  BJGG/BJGG/BbajiSpot/UI Component/InfoDescriptionView.swift
  BJGG/BJGG/BbajiSpot/UI Component/LiveMarkView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraStandbyView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotTodayWeatherCollectionViewCell.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotWeatherAPIInfoView.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotWeatherInfoView.swift
Labels: 🔨 Refactor

#191 [2023/03/23] feat/NetworkCheck >> Network 상태 판별 기능 추가
  BJGG/BJGG.xcodeproj/project.pbxproj
  BJGG/BJGG/BbajiHome/BbajiHomeViewController.swift
  BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
  BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
  BJGG/BJGG/Network/NetworkManager.swift
  BJGG/BJGG/SceneDelegate.swift
Labels: ✨ Feat
